pipeline {
    agent none
    
    stages {
        stage("construir") {
            when {
                changeset "**/worker/**"
            }
            agent {
                docker {
                    image 'maven:3.6.1-jdk-8-slim'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                echo 'Compilando la aplicación worker..'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        
        stage("probar") {
            when {
                changeset "**/worker/**"
            }
            agent {
                docker {
                    image 'maven:3.6.1-jdk-8-slim'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                echo 'Ejecutando pruebas unitarias en la aplicación worker..'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        
        stage("empaquetar") {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            agent {
                docker {
                    image 'maven:3.6.1-jdk-8-slim'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                echo 'Empaquetando la aplicación worker'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
        
        stage('empaquetar-con-docker') {
            agent any
            when {
                changeset "**/worker/**"
                branch 'master'
            }
            steps {
                echo 'Empaquetando la aplicación worker con Docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                        def workerImage = docker.build("xxxxx/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                        workerImage.push("latest")
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo 'La construcción del pipeline multibranch para worker ha sido completada..'
        }
    }
}

